### ISSUE TITLE
Hello i have a problem with plugin!

### ISSUE THREAD

**Issue by mrrat1337** [czQery/ToolKit#8] opened 2022-08-29 16:05 UTC
When i try to give command /pinfo to a player , the command no appear to me 
![image](https://user-images.githubusercontent.com/39533194/187244810-05384419-d312-4133-95a2-9e4e4a13e146.png)

**Comment by czQery** [comment] 2022-08-29 16:42
What server version do you use? (vanilla, paper, purpur, bukkit)
Its working fine for me on paper-1.19.2-135, both in console and ing-game
Also do you have permissions for the command?
![image](https://user-images.githubusercontent.com/60880179/187251480-4c703fbd-8b8e-40c2-b68b-b695a6078427.png)

**Comment by mrrat1337** [comment] 2022-08-29 17:46
bukkit.

**Comment by czQery** [comment] 2022-08-29 18:17
I've managed to reproduce your problem.
I am using some library that isn't in bukkit.
I'll try to replace it with another one but considering how little bukkit is used I don't know if it's even worth it.

So the best way to solve the problem is just to use Paper, it is better in terms of performance and optimization.
(unless you have a specific reason for using bukkit.)

**Comment by mrrat1337** [comment] 2022-08-29 18:24
i maked a server  with spigot
and is the same thing with bukkit.

**Comment by czQery** [comment] 2022-08-29 21:28
Fixed in latest release: https://github.com/czQery/ToolKit/releases/tag/v3.7
At least I hope so.

**Closed by czQery** 2022-08-29 21:28 UTC
Labels: bug

**Comment by mrrat1337** [comment] 2022-08-31 08:40
thanks,worked.
